version: "2"

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_USER: docker
      MYSQL_PASSWORD: 21280712
      MYSQL_DATABASE: incentknow
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      TZ: 'Asia/Tokyo'
    command: "mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --skip-name-resolve"
    volumes:
      - /mnt/incentknow/mysql:/var/lib/mysql
      - ./server/mysql/conf.d:/etc/mysql/conf.d
    ports:
      - 3306:3306
    restart: always

  api:
    environment:
      ENV_SETTINGS: production
      ELASTICSEARCH_NODE: "http://elasticsearch:9200"
      PORT: 8081
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /mnt/incentknow/files:/code/backend/public/uploaded
    ports:
      - 8081:8081
    depends_on:
      - db
      - elasticsearch
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.1
    environment:
      - node.name=es01
      - node.master=true
      - node.data=true
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    volumes:
      - /mnt/incentknow/elasticsearch:/usr/share/elasticsearch/data

  apache2:
    environment:
      APACHE_RUN_USER: www-data
      APACHE_RUN_GROUP: www-data
      APACHE_PID_FILE: /var/run/apache2.pid
      APACHE_RUN_DIR: /var/run/apache2
      APACHE_LOG_DIR: /var/log/apache2
      APACHE_LOCK_DIR: /var/lock/apache2
    build:
      context: .
      dockerfile: Dockerfile_apache2
    volumes:
      - /mnt/incentknow/apache2/log:/var/log/apache2
      - /etc/letsencrypt:/etc/letsencrypt
      - ../codestar:/var/www/codestar.dev
    ports:
      - 80:80