version: "2"

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_USER: docker
      MYSQL_PASSWORD: 21280712
      MYSQL_DATABASE: incentknow
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      TZ: 'Asia/Tokyo'
    command: "mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --skip-name-resolve"
    volumes:
      - /mnt/hdd/incentknow:/var/lib/mysql
      - ./db/conf.d:/etc/mysql/conf.d
    ports:
      - "3306:3306"
    restart: always

  api:
    environment:
      ENV_SETTINGS: production
      PORT: 8081
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - db
      - elasticsearch
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
    environment:
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    volumes:
      - /mnt/hdd/elasticsearch:/usr/share/elasticsearch/data