FROM ubuntu
# FROM node:14-alpine3.13

RUN apt-get update -y && \
    apt-get install -y tzdata && \
    apt-get install -y apache2 && \
    a2enmod rewrite
# mod_rewrite を有効にする
# .htaccess内のRewriteEngineを使用可能にする

# ビルド環境
RUN apt install -y nodejs
RUN npm install -g purescript spago uglifyjs less 

COPY /server/apache2 /etc/apache2

COPY /frontend/src /code
COPY /frontend/public /code/dist
COPY /frontend/spago.dhall /code
COPY /frontend/packages.dhall /code

WORKDIR /code

RUN cp public/.htaccess dist/.htaccess
RUN cp public/assets dist/assets
RUN cp public/index.dist.html dist/index.html
RUN sed -i "" "s/VERSION/$RANDOM/" dist/index.html

RUN spago bundle-app --main Incentknow.Main --to dist/index.js
RUN uglifyjs --compress --mangle -b beautify=false,ascii_only=true -o dist/index.js -- dist/index.js
RUN lessc -x public/less/Main.less dist/index.css
RUN rmdir public/less
RUN mv /dist /var/www/incentknow.com

EXPOSE 80

CMD ["apachectl", "-D", "FOREGROUND"]